proxy:
  landing-page: /app_direct/01_gating
  port: 8080
  authentication: none
  hide-navbar: true
  heartbeat-rate: 10000
  heartbeat-timeout: 90000
  docker:
      internal-networking: true
  specs:
  - id: 01_gating
    display-name: Manual Gating
    description: Application to do manual gating on cytometry data
    container-cmd: ["R", "-e", "gating::run_app()"]
    container-image: 781462664882.dkr.ecr.ap-southeast-1.amazonaws.com/gating:latest
    container-network: sp-net
  - id: 02_gating
    display-name: Manual Gating
    description: Application to do manual gating on cytometry data
    container-cmd: ["R", "-e", "gating::run_app()"]
    container-image: 781462664882.dkr.ecr.ap-southeast-1.amazonaws.com/gating:develop
    container-network: sp-net
logging:
  file:
    shinyproxy.log
